auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  replication_factor: 1

  # ใช้ memberlist เป็น kvstore สำหรับ ring (ไม่ต้องใช้ Consul)
  ring:
    kvstore:
      store: memberlist

  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules

# config สำหรับ single-process TSDB backend
schema_config:
  configs:
    - from: 2023-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /loki/data

# memberlist สำหรับ ring ภายในเครื่องเดียว
memberlist:
  join_members: [] # single node ไม่ต้อง join ใคร
  abort_if_cluster_join_fails: false
  bind_port: 7946

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true

limits_config:
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  allow_structured_metadata: false
  max_entries_limit_per_query: 500000

ruler:
  rule_path: /loki/rules-temp
  storage:
    local:
      directory: /loki/rules
  alertmanager_url: ""
  enable_api: true
