repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
  - repo: local
    hooks:
      - id: remove-pindata
        name: Remove pinData
        entry: python scripts/remove_pin_data.py
        language: python
        files: ^workflows/.*\.json$
        stages: [commit]
