global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "n8n"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["n8n:5678"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
