apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: df52ybijafbwgd
    isDefault: true
    jsonData:
      timeInterval: 5s

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: df4h027p5cohsd
    jsonData:
      maxLines: 1000
